'''solar'''

def solar():
    '''solution'''
    text = input() + ' '
    temp, hot, cold, left_star, right_star = temp_maker(text, ''), '', '', None, None
    n_star, previous, previous_star, sun_pos = 0, -1, '', 0
    buffer = ''

    # Loop through the temp string generated by temp_maker
    i = 0
    while i < len(temp):
        if temp[i] == ' ':
            n_star += 1
            # Extracting the name of the current star
            current = text[previous + 1:int(buffer)]
            if left_star is None:
                left_star = current + ' '
            if current == 'Sun':
                hot += previous_star + ' '
                sun_pos = n_star
            if previous_star == 'Sun':
                hot += current
            previous, previous_star = int(buffer), current
            buffer = ''
        elif temp[i].isdigit():
            buffer += temp[i]
        i += 1

    if right_star is None:
        right_star = previous_star

    # Determine the cooler star(s)
    if text.strip() != 'Sun':
        if abs(1 - sun_pos) > abs(n_star - sun_pos):
            cold = left_star
        elif abs(1 - sun_pos) == abs(n_star - sun_pos):
            cold = left_star + right_star
        else:
            cold = right_star

    # Output the results
    print(f"Hot: {hot.strip()}")
    print(f"Cool: {cold.strip()}")


def temp_maker(text, temp):
    '''Generate Temp Data'''
    i = 0
    while i < len(text):
        if i > 2 and text[i - 3:i + 1] == 'Sun ':
            temp += str(i) + ' '
        elif text[i] == ' ' and text[i - 3:i + 1] != 'Sun ':
            temp += str(i) + ' '
        i += 1
    return temp

solar()
